.\" manpage for mpetUI
.\" Contact sayalaso@purdue.edu to correct errors or typos
.TH mpetUI.py "12 Deecmber 2019" "version 0.1" "mpetUI manpage"
.SH NAME
mpetUI - Graphical and command-line interface for MPET (Multiphase Porous Electrode Theory)
.SH SYNOPSIS
.B $mpetUI
.RI "[--help,--quit,--gui,--parameters=values]"
.SH DESCRIPTION
.B mpetUI
is a user interface (UI) developed to run mpet in either GUI mode (using the --gui option),or using the command-line interface by passing --parameters. MPET (Multiphase Porous Electrode Theory) is designed to run simulations of batteries with porous electrodes using porus electrode theory. MPET was developed by Raymond Smith [1]. The mpetUI also uses the VKML library, which was developed by Alex Bartol [3].    
.PP
.B mpetUI 
runs on python 3.6.
.PP
.B [1] 
Smith, R. B., and Bazant M. Z., Multiphase Porous Electrode Theory, [Journal of the Electrochemical Society] (https://doi.org/10.1149/2.0171711jes), 2017, 164 (11) E3291-E3310, [arXiv preprint](https://arxiv.org/abs/1702.08432)
.PP
.B [2] 
Ferguson, Todd R., and Martin Z. Bazant. "Phase transformation dynamics in porous battery electrodes." Electrochimica Acta 146 (2014): 89-97.
.PP
.B [3]
Bartol, A., Ely, D. R., Guyer, J., García, R. E. The Virtual Kinetics of Materials Laboratory. 2015.
.PP
.B [4]
Martin Z. Bazant, "Theory of Chemical Kinetics and Charge Transfer based on Nonequilibrium Thermodynamics". Accounts of Chemical Research 2013 46 (5), 1144-1160 DOI: 10.1021/ar300145c 
.PP
.B [5]
Fuller, Thomas F., Marc Doyle, and John Newman. "Simulation and optimization of the dual lithium ion insertion cell." Journal of the Electrochemical Society 141.1 (1994): 1-10.
.PP
.B [6]
Y. Zeng, R. Smith, P. Bai, and M. Z. Bazant, Simple formula for asymmetric Marcus-Hush kinetics, J. Electroanal. Chem. 748, 52-57 (2015)
.PP
.B [7]
Bernardi, Dawn M., and Joo-Young Go. "Analysis of pulse and relaxation behavior in lithium-ion batteries." Journal of Power Sources 196.1 (2011): 412-427.
.PP
.B [8]
K.C. Smith, P.P. Mukherjee, T.S. Fisher, Columnar order in jammed LiFePO4 cathodes: ion transport catastrophe and its mitigation, Phys. Chem. Chem. Phys. 14 (2012) 7040–7050, doi:10.1039/C2CP40135E.
.SH OPTIONS
.TP
.B "--help"
	Prints a description of all the parameters used in mpetUI(this page).
.TP
.B "--quit"
	Quits the UI.
.TP
.B "--gui"
	Runs the UI in interactive GUI mode.
.TP
.B "--parameters=values"
.RB "The parameter/s required to run an mpet simulation through UI are passed using these options. The parameters are summerized next, units associated to each parameters are written at the end as [units]. The parameters are grouped according to their arrangement in parameter cigurationles from the mpet legacy mode." 
.PP
.RS
.B "Note:"
The parameter names used in the cigurationles to run mpet in legacy mode are differnt from the UI parameter names. So, the legacy mode parameter names are mentioned along with the UI parameter defninitions for the ease of user to run mpet in legacy mode.   
.TP
.B "--Anode_config_file"  
Specify the Anode parameter cigurationle
.TP
.B "--Cathode_config_file"  
Specify the Cathode parameter cigurationle
.TP
.B "--System_config_file"  
Specify the System parameter cigurationle
.TP
.I "ANODE PARTICLE PARAMETERS"
.TP
.B "--anode_particle"  

.RS
Type of solid particles for anode (legacy mode: "type") [-]

Options:
 - ACR -- "Allen-Cahn-Reaction" particles. Use ONLY with shape = C3.
 - CHR -- "Cahn-Hilliard-Reaction". Currently required shape = sphere or cylinder.
 - CHR2 -- 2-concentrationeld "Cahn-Hilliard-Reaction". 
          Currently required shape = sphere or cylinder.
 - homog -- homogeneouslylling particles
 - homog_sdn -- homogeneouslylling particles with size-dependent
   nucleation (see Ferguson and Bazant, 2014, Electrochimica Acta)[2]
   (ignores Omega_a and only works for LFP, ONLY use with isothermal
   298 K and C3 shape)
 - homog2 -- 2-concentrationeld model like CHR2 but each layer is
   treated as homogeneous rather than having transport within each
   layer
 - diffn -- Particles with rxn at surface and internal solid diffusion
   WARNING: Using diffn model with BV reaction model assumes surface
   activity is given by c/(1-c), c =lling fraction, when
   calculating the reaction rate exchange current density. Consider,
   e.g., BV_mod01 instead.
.RE

.TP
.B "--anode_particle_discretization" 

.RS 
Discretization of solid (legacy mode: "discretization") [m] 
   Used for non-homogeneous type
   When using phase separating particles, must be less than characteristic 
   interface width, lambda_b: 
   lambda_b = (kappa/(rho_s*Omega_a))^(0.5)) [Bazant 2013]
.RE

.TP
.B "--anode_particle_shape"  

.RS
Shape of the anode particle (legacy mode: "shape") [-]

Options: sphere, C3, cylinder
  - sphere -- spherical paricle react on entire surface area
  - C3 -- nano platelet type particle react along b surface [1,8]
  - cylinder -- cylindrical particle react on surfaces with radial normal.
.RE

.TP
.B "--anode_particle_thickness" 

.RS 
a-axis length for C3 particle or diameter of cylindrical and spherical particle (legacy mode: "shape") [m]
.RE

.TP
.I "ANODE MATERIAL PARAMETERS"
.TP
.B "--anode_material_muRfunc"

.RS
The chemical potential of the reduced state as a function oflling fraction (the electron conducting phase, usually solid) as a function oflling fraction. (legacy mode: "muRfunc") [-]

-Options: 
  LiC6_coke_ss2, LiC6, LiMn2O4_ss, LiMn2O4_ss2, LiC6_coke_ss, LiC6_ss, LiC6_ss2, LiC6_2step_ss, Li_ss, NCA_ss1, NCA_ss2, testIS_ss,testRS_ss, ideal_sln, reg_sln, graphite_2param_homog, graphite_1param_homog, graphite_1param_homog_2, non_homog_rectxed_csurf, non_homog_round_wetting, general_non_homog, LiFePO4, LiC6_1param, testRS, "testRS_ps"
.RE

.TP
.B "--anode_material_Logpad"  
.RS
Log pad (option for muRfuncs containing log terms -- not solid solution) (legacy mode: "logPad")[-]
  Consider turning this on if you experience errors with log of negative terms. It extends the ideal solution into regions outside (0, 1) by a (very steep) linear extension instead of a singularity.
  default=false
-Options: 
  true, false
.RE

.TP
.B "--anode_material_noise"  

.RS
Add Langevin noise to the solid dynamics to simulate some random thermal fluctuations. (legacy mode: "noise") [-]
  This can help to, e.g., trigger a spinodal decomposition but 
  slows simulations so should not be enabled unless needed.
  default=false
Options: true, false
.RE

.TP
.B "--anode_material_mag_noise"

.RS  
Magnitude of the noise (used if anode_material_noise = true). (legacy mode: "noise_prefac") [-]
The standard deviation of the normal noise added to the solid dynamics
.RE

.TP
.B "--anode_material_num_noise"  
Number of segments over which the noise is re-randomized. (legacy mode: "num_noise") [-]
.TP
.B "--anode_material_oma "  

.RS
Regular solution parameter[1]. (legacy mode: "Omega_a")[J/Li]
Note k*298 K = 4.115e-21 J/particle
Default = 4.51 (k*298 K) [J/Li]
.RE

.TP
.B "--anode_material_omb"  
Secondary interaction terms for 2-variable models (legacy mode: "Omega_b")[J/Li]
.TP
.B "--anode_material_omc"  
Secondary interaction terms for 2-variable models (legacy mode: "Omega_c")[J/Li]
.TP
.B "--anode_material_grad_pen"  
Gradient penalty (legacy mode: "kappa") [J/m]
.TP
.B "--anode_material_stress_coeff"  
Stress coecient (legacy mode: "B") [Pa] 
.TP
.B "--anode_material_EvdW"
Van der Waals-like interaction energy for graphite models (legacy mode: "EvdW") [J/Li]
.TP
.B "--anode_material_rho_s"

.RS
Total Li site density within the solid, (legacy mode: "rho_s")[Li/m^3]
Even for 2-parameter models, this should be the full site density
(not that of an individual layer/lattice)
.RE

.TP
.B "--anode_material_D"
Dimensional diffusivity prefactor (used if anode_particle_type = diffn[2], CHR[2]) (legacy mode: "D") [m^2/s]
.TP
.B "--anode_material_Dfunc"

.RS
Dimensionless diffusivity function (legacy mode: "Dfunc") [-]
  This is a function of solidlling fraction, y, such that
  Flux = -D*Dfunc(y)*grad(c) for solid solution materials, and
  Flux = -D*Dfunc(y)*grad(mu) for thermo-based transport models
  Options: constant,lattice
.RE

.TP
.B "--anode_material_dgammadc"

.RS
Surface wetting ,used if anode_particle_type = CHR2. (legacy mode: "dgammadc") [J*m/Li]
  Change in surface energy with respect to solid concentration, 
  set greater than 0 for surface wetting, less than 0 for dewetting
  default: 0e-30
.RE

.TP
.B "--anode_material_cwet"
Dimensionless surface wetting used with LiFePO4, anode_particle_type=ACR. (legacy mode: "cwet") [-]
.TP
.I "ANODE REACTION PARAMETERS"
.TP
.B "--anode_reaction_type"

.RS
anode particle reaction type (legacy mode: "rxnType") [-]
 Options:
  - BV: Butler-Volmer from Bazant Acc. Chem. Res. 2013 with gamma_TS = 1/(1-c) [4]
  - BV_gMod01: Like BV with gamma_TS = 1/(c*(1-c))
  - BV_raw: BV with ecd = k0
  - BV_mod01: As in Fuller, Doyle, Newman 1994 cathode [5]
  - BV_mod02: As in Fuller, Doyle, Newman 1994 anode [5]
  - Marcus: As in Bazant Acc. Chem. Res. 2013 [4]
  - MHC: See Zeng, Smith, Bai, Bazant, 2014 [6]
.RE

.TP
.B "--anode_reaction_ecd"

.RS
Exchange current density (legacy mode: "k0") [A/m^2] 
(0.1 for h2/Pt). Note, for Marcus, this is k0 * exp(-(lambda/kTref)/4)
.RE

.TP
.B "--anode_reaction_charget"
Charge transfer coecient (only used for BV) (legacy mode: "alpha") [-]
.TP
.B "--anode_reaction_Rorg_energy"

.RS
Reorganizational energy used for Marcus and MHC (legacy mode : "lambda") [J/Li]
default= 15.2(k*298) K
.RE

.TP
.B "--anode_reactionlmres"
Film resistance (legacy mode:"lm") [Ohm m^2]
.TP
.I "CATHODE PARTICLE PARAMETERS"
.TP
.B "--cathode_particle"  

.RS
Type of solid particles for cathode (legacy mode: "type") [-]

Options:
 - ACR -- "Allen-Cahn-Reaction" particles. Use ONLY with shape = C3.
 - CHR -- "Cahn-Hilliard-Reaction". Currently required shape = sphere or cylinder.
 - CHR2 -- 2-concentrationeld "Cahn-Hilliard-Reaction". 
          Currently required shape = sphere or cylinder.
 - homog -- homogeneouslylling particles
 - homog_sdn -- homogeneouslylling particles with size-dependent
   nucleation (see Ferguson and Bazant, 2014, Electrochimica Acta)[2]
   (ignores Omega_a and only works for LFP, ONLY use with isothermal
   298 K and C3 shape)
 - homog2 -- 2-concentrationeld model like CHR2 but each layer is
   treated as homogeneous rather than having transport within each
   layer
 - diffn -- Particles with rxn at surface and internal solid diffusion
   WARNING: Using diffn model with BV reaction model assumes surface
   activity is given by c/(1-c), c =lling fraction, when
   calculating the reaction rate exchange current density. Consider,
   e.g., BV_mod01 instead.
.RE

.TP
.B "--cathode_particle_discretization" 

.RS 
Discretization of solid (legacy mode: "discretization") [m] 
   Used for non-homogeneous type
   When using phase separating particles, must be less than characteristic 
   interface width, lambda_b: 
   lambda_b = (kappa/(rho_s*Omega_a))^(0.5)) [Bazant 2013]
.RE

.TP
.B "--cathode_particle_shape"  

.RS
Shape of the cathode particle (legacy mode: "shape") [-]

Options: sphere, C3, cylinder
  - sphere -- spherical paricle react on entire surface area
  - C3 -- nano platelet type particle react along b surface [1,8]
  - cylinder -- cylindrical particle react on surfaces with radial normal.


.RE

.TP
.B "--cathode_particle_thickness" 

.RS 
a-axis length for C3 particle or diameter of cylindrical and spherical particle (legacy mode: "shape") [m]
.RE

.TP
.I "CATHODE MATERIAL PARAMETERS"
.TP
.B "--cathode_material_muRfunc"

.RS
The chemical potential of the reduced state as a function oflling fraction (the electron conducting phase, 
usually solid) as a function oflling fraction. (legacy mode: "muRfunc") [-]

Options: LiC6_coke_ss2, LiC6, LiMn2O4_ss, LiMn2O4_ss2, LiC6_coke_ss, LiC6_ss, LiC6_ss2, LiC6_2step_ss, Li_ss, NCA_ss1,
  NCA_ss2, testIS_ss, testRS_ss, ideal_sln, reg_sln, graphite_2param_homog, graphite_1param_homog, 
  graphite_1param_homog_2, non_homog_rectxed_csurf, non_homog_round_wetting, general_non_homog, LiFePO4,
  LiC6_1param, testRS, "testRS_ps"
.RE

.TP
.B "--cathode_material_Logpad"  

.RS
Log pad (option for muRfunc"s containing log terms -- not solid solution) (legacy mode: "logPad")[-]
  Consider turning this on if you experience errors with log of negative terms
  It extends the ideal solution into regions outside (0, 1) by a
  (very steep) linear extension instead of a singularity.
  default=false
Options: true, false
.RE

.TP
.B "--cathode_material_noise"  

.RS
Add Langevin noise to the solid dynamics to simulate some random thermal fluctuations. (legacy mode: "noise") [-]
  This can help to, e.g., trigger a spinodal decomposition but slows simulations so should not be
  enabled unless needed.
  default=false
Options: true, false
.RE

.TP
.B "--cathode_material_mag_noise"

.RS  
Magnitude of the noise (used if cathode_material_noise = true). (legacy mode: "noise_prefac") [-]
The standard deviation of the normal noise added to the solid dynamics
.RE

.TP
.B "--cathode_material_num_noise"  
Number of segments over which the noise is re-randomized. (legacy mode: "num_noise") [-]
.TP
.B "--cathode_material_oma "  

.RS
Regular solution parameter[1]. (legacy mode: "Omega_a")[J/Li]
Note k*298 K = 4.115e-21 J/particle
Default = 4.51 (k*298 K) [J/Li]
.RE

.TP
.B "--cathode_material_omb"  
Secondary interaction terms for 2-variable models (legacy mode: "Omega_b")[J/Li]
.TP
.B "--cathode_material_omc"  
Secondary interaction terms for 2-variable models (legacy mode: "Omega_c")[J/Li]
.TP
.B "--cathode_material_grad_pen"  
Gradient penalty (legacy mode: "kappa") [J/m]
.TP
.B "--cathode_material_stress_coeff"  
Stress coecient (legacy mode: "B") [Pa] 
.TP
.B "--cathode_material_EvdW"
Van der Waals-like interaction energy for graphite models (legacy mode: "EvdW") [J/Li]
.TP
.B "--cathode_material_rho_s"

.RS
Total Li site density within the solid, (legacy mode: "rho_s")[Li/m^3]
Even for 2-parameter models, this should be the full site density
(not that of an individual layer/lattice)
.RE

.TP
.B "--cathode_material_D"
Dimensional diffusivity prefactor (used if cathode_particle_type = diffn[2], CHR[2]) (legacy mode: "D") [m^2/s]
.TP
.B "--cathode_material_Dfunc"

.RS
Dimensionless diffusivity function (legacy mode: "Dfunc") [-]
  This is a function of solidlling fraction, y, such that
  Flux = -D*Dfunc(y)*grad(c) for solid solution materials, and
  Flux = -D*Dfunc(y)*grad(mu) for thermo-based transport models
  Options: constant,lattice
.RE

.TP
.B "--cathode_material_dgammadc"

.RS
Surface wetting ,used if cathode_particle_type = CHR2. (legacy mode: "dgammadc") [J*m/Li]
  Change in surface energy with respect to solid concentration, 
  set greater than 0 for surface wetting, less than 0 for dewetting
  default: 0e-30
.RE

.TP
.B "--cathode_material_cwet"
Dimensionless surface wetting used with LiFePO4, cathode_particle_type=ACR. (legacy mode: "cwet") [-]
.TP
.I "CATHODE REACTION PARAMETERS"
.TP
.B "--cathode_reaction_type"

.RS
cathode particle reaction type (legacy mode: "rxnType") [-]
 Options:
  - BV: Butler-Volmer from Bazant Acc. Chem. Res. 2013 with gamma_TS = 1/(1-c) [4]
  - BV_gMod01: Like BV with gamma_TS = 1/(c*(1-c))
  - BV_raw: BV with ecd = k0
  - BV_mod01: As in Fuller, Doyle, Newman 1994 cathode [5]
  - BV_mod02: As in Fuller, Doyle, Newman 1994 cathode [5]
  - Marcus: As in Bazant Acc. Chem. Res. 2013 [4]
  - MHC: See Zeng, Smith, Bai, Bazant, 2014 [6]
.RE

.TP
.B "--cathode_reaction_ecd"

.RS
Exchange current density (legacy mode: "k0") [A/m^2] 
(0.1 for h2/Pt). Note, for Marcus, this is k0 * exp(-(lambda/kTref)/4)
.RE

.TP
.B "--cathode_reaction_charget"
Charge transfer coecient (only used for BV) (legacy mode: "alpha") [-]
.TP
.B "--cathode_reaction_Rorg_energy"

.RS
Reorganizational energy used for Marcus and MHC (legacy mode : "lambda") [J/Li]
default= 15.2(k*298) K
.RE

.TP
.B "--cathode_reactionlmres"
Film resistance (legacy mode:"lm") [Ohm m^2]
.TP
.I "SYSTEM PARAMETERS"
.TP
.B "--sim_pars_prof"
 
.RS
Constant voltage or current or segments of one of them (legacy mode: "prleType") [-]
 Options: CV (constant voltage), CC (constant current), CCsegments, CVsegments
.RE

.TP
.B "--sim_pars_crate"

.RS
Battery (dis)charge c-rate (only used for CC) (legacy mode: "Crate") [1/hr]
(positive for discharge, negative for charge)
.RE

.TP
.B "--sim_pars_Vcutmax" 
Maximum Voltage cutoff (legacy mode: "Vmax") [V]
.TP
.B "--sim_pars_Vcutmin"
Minimum Voltage cutoff (legacy mode: "Vmin") [V]
.TP
.B "--sim_pars_capfrac"

.RS
Fraction of full (dis)charge to simulate (only used for CC) (legacy mode: "capFrac") [-]
  E.g. to go from cathodelling fraction 0.1 to 0.5 with cathode
  limiting capacity and Crate>0, set cs0_c = 0.1, capFrac=0.4
.RE

.TP
.B "--sim_pars_applv"
Battery applied voltage (only used for CV) (legacy mode: "Vset") [V]
.TP
.B "--sim_pars_segments"

.RS
CC/CV segments dning prle for sim_pars_prof = CCsegments or CVsegments  (legacy mode: "segments")[(a,b),(c,d),(e,f)]
 Segments are input as a list of tuples, with therst entry of each
 row being the setpoint (CC or CV) and the second being the time (in
 minutes) for which that setpoint is held.
 This can have as many segments as desired.
.RE

.TP
.B "--sim_pars_rampt"

.RS
  Ramp time to go from near-eq"m initial condition to setpoint for
  CC/CV, as a fraction of total simulation time, non-dimensional or
  Ramp time to linearly transition to each new segment for
  CCsegments/CVsegments                                       (legacy mode: "tramp") [s]
.RE

.TP
.B "--sim_parsntime"
Final time (only used for CV)  (legacy mode: "tend")[s]
.TP
.B "--sim_pars_numdisc"
Number of time steps   (legacy mode: "tsteps") [-]
  Time stepping is adaptive, variable-order stepping, so this
  affects only the interpolated output values, not simulation
  accuracy. The output will have all simulation values at a linear
  spacing between initial andnal times with tsteps total outputs.
.TP
.B "--sim_pars_reltol"
Relative Tolerance.  (legacy mode: "relTol") [-]
.TP
.B "--sim_pars_abstol"
Absolute Tolerance.  (legacy mode: "absTol") [-]
.TP
.B "--sim_pars_temp"

.RS
Temperature, (legacy mode: "T") [K]
  WARNING -- temperature dependence not fully implemented. Use 298 K.
.RE

.TP
.B "--sim_pars_randseed"

.RS
Random seed. Set to true to give a random seed in the simulation (affects noise, particle size distribution) (legacy mode: "randomSeed") [-]
  Set to true exactly reproducible results -- useful for testing. 
  Options: true, false
.RE

.TP
.B "--sim_pars_seed"
Value of the random seed, must be an integer (legacy mode: "seed") [-]
.TP
.B "--sim_pars_Rseries"
Series resistance, (legacy mode: "Rser") [Ohm m^2]
.TP
.B "--sim_pars_cat_numdisc"
Cathode numerical discretization in x direction. (legacy mode: "Nvol_c") [-]
.TP
.B "--sim_pars_sep_numdisc"
Seperator numerical discretization in x direction. (legacy mode: "Nvol_s") [-]
.TP
.B "--sim_pars_an_numdisc"
Anode numerical discretization in x direction. (legacy mode: "Nvol_a") [-]
.br
Cathode, anode, and separator numer disc. in x direction(volumes in electrodes) Nvol_c must be >= 1.If Nvol_c = 1 & Nvol_a = 0 & Nvol_s = 0, simulate a single volume with no separator and initely fast counter electrode. If Nvol_a = 0, simulate a Li foil electrode
.TP
.B "--sim_pars_cat_nPartVol"
Number of particles per volume for cathode (legacy mode: "Npart_c") [-]
.TP
.B "--sim_pars_an_nPartVol"
Number of particles per volume for anode (legacy mode: "Npart_a") [-]
.TP
.I "SYSTEM ELECTRODE PARAMATERS"
.TP
.B "--sim_elect_rc_Lifoil"

.RS
Rate constant of the Li foil electrode, (legacy mode: "k0_foil")[A/m^2] 
Used only if  sim_pars_an_numdisc = 0
.RE

.TP
.B "--sim_elect_Lifoillmres"
Film resistance on the Li foil, (legacy mode: "lm_foil")[Ohm m^2]
.TP
.I "SYSTEM PARTICLE DISTRIBUTION PARAMETERS"
.TP

electrode particle size distribution info, [m]
 C3 -- size along [100] direction 
 sphere or cylinder -- radius. 
 If using stddev = 0, set Npart = 1 for that electrode to avoid wasting computational effort


.TP
.B "--sim_PartDist_cat_mean" 
Mean of cathode particle size distribution (legacy mode: "mean_c") [m]
.TP
.B "--sim_PartDist_cat_std"
standard deviation of cathode particle size distribution (legacy mode: "stddev_c") [m]
.TP
.B "--sim_PartDist_an_mean"
Mean of anode particle size distribution (legacy mode: "mean_a") [m]
.TP
.B "--sim_PartDist_an_std"
standard deviation of anode particle size distribution (legacy mode: "stddev_a") [m]
.TP
.B "--sim_PartDist_catllfrac"
Initial cathodelling fraction (legacy mode: "cs0_c") [-]
.TP
.B "--sim_PartDist_anllfrac"
Initial anodelling fraction (legacy mode: "cs0_a") [-]
.TP
.R "for discharge, anode starts full, cathode starts empty"
.TP
.I "SYSTEM CONDUCTIVITY PARAMETERS"
.TP
.B "--sim_cond_cat_bulk_par"
Simulate bulk cathode conductivity (Ohm"s Law?)(True/False) (legacy mode: "simBulkCond_c") [-]
.TP
.B "--sim_cond_an_bulk_par"
Simulate bulk anode conductivity (Ohm"s Law)(True/False) (legacy mode: "simBulkCond_a") [-]
.TP
.B "--sim_cond_cat_bulk"
Dimensional conductivity of cathode (used if sim_cond_cat_bulk_par = true), (legacy mode: "sigma_s_c") [S/m]
.TP
.B "--sim_cond_an_bulk"
Dimensional conductivity of anode (used if sim_cond_an_bulk_par= true),(legacy mode: "sigma_s_a") [S/m]
.TP
.B "--sim_cond_cat_connect_par"

.RS
Simulate particle connectivity losses in cathode (Ohm"s Law?) (legacy mode: "simPartCond_c") [-]
options: (True/False)
.RE

.TP
.B "--sim_cond_an_connect_par"

.RS
Simulate particle connectivity losses in anode (Ohm"s Law?) (legacy mode: "simPartCond_a") [-]
options: (True/False)
.RE

.TP
.B "--sim_condpart_cat_mean" 
mean Conductance between cathode particles, (legacy mode: "G_mean_c") [S = 1/Ohm]
.TP
.B "--sim_condpart_cat_std"
standard deviation in Conductance between cathode particles, (legacy mode: "G_stddev_c") [S = 1/Ohm]
.TP
.B "--sim_condpart_an_mean"
mean Conductance between anode particles,(legacy mode: "G_mean_a") [S = 1/Ohm]
.TP
.B "--sim_condpart_an_std"
standard deviation in Conductance between anode particles,(legacy mode: "G_stddev_a") [S = 1/Ohm]
.TP
.I " SYSTEM GEOMETRY PARAMETERS"
.TP
.B "--sim_geo_cat_thickness"
Cathode thickness, (legacy mode: "L_c") [m]
.TP
.B "--sim_geo_an_thickness"
Anode thickness,(legacy mode: "L_a") [m]
.TP
.B "--sim_geo_sep_thickness"
Seperator thickness (legacy mode: "L_s") [m]
.TP
.B "--sim_geo_cat_volload"
Volume loading percents of active material in cathode(volume fraction of solid that is active material) (legacy mode: "P_L_c") [-]
.TP
.B	"--sim_geo_an_volload"
Volume loading percents of active material in anode(volume fraction of solid that is active material) (legacy mode: "P_L_a") [-]
.TP
.B "--sim_geo_cat_por"
Porosity of cathode (liquid volume fraction in cathode) (legacy mode: "poros_c") [-]
.TP
.B "--sim_geo_an_por"
Porosity of anode (liquid volume fraction in anode) (legacy mode: "poros_a") [-]
.TP
.B "--sim_geo_sep_por"
Porosity of seperator (liquid volume fraction in seperator) (legacy mode: "poros_s") [-]

.TP
.B "--sim_geo_cat_Brug"
Bruggeman exponent for cathode (tortuosity = porosity^bruggExp) (legacy mode: "BruggExp_c") [-]
.TP
.B "--sim_geo_an_Brug"
Bruggeman exponent for anode (tortuosity = porosity^bruggExp) (legacy mode: "BruggExp_a") [-]
.TP
.B "--sim_geo_sep_Brug"
Bruggeman exponent for seperator (tortuosity = porosity^bruggExp) (legacy mode: "BruggExp_s") [-]
.TP
.I "SYSTEM ELECTROLYTE PROPERTIES"
.TP
.B "--sim_elprop_InConc"
Initial electrolyte concentration, (legacy mode: "c0") [mol/m^3]
.TP
.B "--sim_elprop_cation_chargeNum"
Cation/anion charge number (e.g. 2, -1 for CaCl_2) (legacy mode: "zp") [-]
.TP
.B "--sim_elprop_anion_chargeNum"
Cation/anion charge number (e.g. 2, -1 for CaCl_2) (legacy mode: "zm") [-]
.TP
.B "--sim_elprop_disNup"
Cation/anion dissociation number (e.g. 1, 2 for CaCl_2) (legacy mode: "nup") [-]
.TP
.B "--sim_elprop_disNum"
Cation/anion dissociation number (e.g. 1, 2 for CaCl_2) (legacy mode: "num") [-]	  
.TP
.B "--sim_elprop_model"

.RS
Electrolyte model, (legacy mode: "elyteModelType") [-]
  Options: dilute, SM
  - dilute -- assume dilute, binary electrolyte model; phi in
    electrolyte is an "inner potential" or an "quasi-electrostatic
    potential"
  - SM -- use Stefan-Maxwell model for electrolyte transport; phi in
    electrolyte is that measured with a Li metal reference electrode
    relative to somexed position in solution.
  WARNING: Using SM model with BV reaction models for electrode
  particles assumes individual ion activities are given by their
  concentrations for the reaction rate exchange current density.
.RE

.TP
.B "--sim_elprop_SMpropset"

.RS
Stefan-Maxwell property set, (legacy mode : "SMset") [-]
  Options:
   - test1 -- parameter set for testing
   - LiClO4_PC -- electrolyte/solvent used in Fuller, Doyle, Newman 1994
                conductivity taken from dualfoil5.2.f [5]
   - valoen_bernardi -- LiPF6 in carbonates as in Bernardi and Go 2011 [7]
.RE

.TP
.B "--sim_elprop_electrans"

.RS
Reference electrode (dning the electrolyte potential) ormation: (legacy mode: "n") [-]
  number of electrons transfered in the reaction, 1 for Li/Li+
.RE

.TP
.B "--sim_elprop_Stoicof"
Stoichiometric coecient of cation, -1 for Li/Li+ (legacy mode: "sp") [-]
.TP
.B "--sim_elprop_catdiff" 
Dilute solution properties (used only if sim_elprop_model = dilute) Cation diffusion, (legacy mode: "Dp") [m^2/s]
.TP
.B "--sim_elprop_andiff"
Dilute solution properties (used only if sim_elprop_model = dilute) anion diffusion, (legacy mode: "Dm") [m^2/s]

.RE

.SH EXAMPLES
A list of mpetUI parameter values to run a default simulation of ( Fulller, Doyle 1994) [5] is as follow:
.PP
.nf
.RS

anode_particle = diffn
anode_particle_discretization = 50e-8
anode_particle_shape = sphere
anode_particle_thickness = 20e-9

anode_material_muRfunc = LiC6_coke_ss2
anode_material_logPad = false
anode_material_noise = false
anode_material_mag_noise = 1e-6
anode_material_num_noise = 200
anode_material_oma = 1.8560e-20
anode_material_omb = 5.761532e-21
anode_material_omc = 8.23076e-20
anode_material_grad_pen = 5.0148e-10
anode_material_stress_coeff = 0.1916e9
anode_material_EvdW = 0.0
anode_material_rho_s = 1.58981e28
anode_material_D = 5e-13
anode_material_Dfunc = constant
anode_material_dgammadc = 0e-30
anode_material_cwet = 0.98

anode_reaction_type = BV_mod02
anode_reaction_ecd = 8.3038
anode_reaction_charget = 0.5
anode_reaction_Rorg_energy = 6.26e-20
anode_reactionlmres = 0e-0

cathode_particle = diffn
cathode_particle_discretization = 5e-8
cathode_particle_shape = sphere
cathode_particle_thickness = 20e-9

cathode_material_muRfunc = LiMn2O4_ss2
cathode_material_logPad = false
cathode_material_noise = false
cathode_material_mag_noise = 1e-6
cathode_material_num_noise = 200
cathode_material_oma = 1.8560e-20
cathode_material_omb = 5.761532e-21
cathode_material_omc = 8.23076e-20
cathode_material_grad_pen = 5.0148e-10
cathode_material_stress_coeff = 0.1916e9
cathode_material_EvdW = 0.0
cathode_material_rho_s = 1.42842e28
cathode_material_D = 1e-13
cathode_material_Dfunc = constant
cathode_material_dgammadc = 0e-30
cathode_material_cwet = 0.98

cathode_reaction_type = BV_mod01
cathode_reaction_ecd = 7.225
cathode_reaction_charget = 0.5
cathode_reaction_Rorg_energy = 6.26e-20
cathode_reactionlmres = 0e-0


sim_pars_prof = CC
sim_pars_crate = .66
sim_pars_Vcutmax = 5
sim_pars_Vcutmin = 2

sim_pars_capfrac = 0.8
sim_pars_applv = 0.12
sim_pars_segments = [(0.3, 0.4),(-0.5, 0.1)]
sim_pars_rampt = 1e-3
sim_parsntime = 1.2e3
sim_pars_numdisc = 200
sim_pars_reltol = 1e-6
sim_pars_abstol = 1e-6
sim_pars_temp = 298
sim_pars_randseed = true
sim_pars_seed = 0
sim_pars_Rseries = 0.
sim_pars_cat_numdisc = 2
sim_pars_sep_numdisc = 2
sim_pars_an_numdisc = 2
sim_pars_cat_nPartVol = 1
sim_pars_an_nPartVol = 1

sim_elect_rc_Lifoil = 1e0
sim_elect_Lifoillmres = 0e-0

sim_PartDist_cat_mean = 1e-6
sim_PartDist_cat_std = 0
sim_PartDist_an_mean = 18e-6
sim_PartDist_an_std = 0

sim_PartDist_catllfrac = 0.2
sim_PartDist_catllfrac = 0.495

sim_cond_cat_bulk_par = false
sim_cond_an_bulk_par = false
sim_cond_cat_bulk = 1e-1
sim_cond_an_bulk = 1e-1
sim_cond_cat_connect_par = false
sim_cond_an_connect_par = false
sim_condpart_cat_mean = 1e-14
sim_condpart_cat_std= 0
sim_condpart_an_mean = 1e-14
sim_condpart_an_std = 0

sim_geo_cat_thickness = 200e-6
sim_geo_an_thickness = 243e-6
sim_geo_sep_thickness = 50e-6

sim_geo_cat_volload = 0.849
sim_geo_an_volload = 0.956

sim_geo_cat_por = 0.3
sim_geo_an_por = 0.3
sim_geo_sep_por = .4

sim_geo_cat_Brug = -0.5
sim_geo_an_Brug = -0.5
sim_geo_sep_Brug = -0.5


sim_elprop_InConc = 1000

sim_elprop_cation_chargeNum = 1
sim_elprop_anion_chargeNum = -1

sim_elprop_disNum = 1
sim_elprop_model = 1

sim_elprop_model = SM
sim_elprop_SMpropset= LiClO4_PC
sim_elprop_electrans= 1
sim_elprop_Stoicof = -1
sim_elprop_catdiff = 2.2e-10
sim_elprop_andiff = 2.94e-10
.RE
.fi
.PP
.RS
.PP
These parameter values can be input into the GUI of mpetUI through  using 
  $mpetUI --gui
OR
.PP
mpetUI can be run in command line mode using the following command.
.PP
  $mpetUI --Sim_pars_crate=0.66 --Sim_pars_Vcutmax=5 --Sim_pars_Vcutmin=2 --Sim_pars_capfrac=0.8
  --Sim_pars_cat_numdisc=2 --Sim_pars_sep_numdisc=2 --Sim_pars_an_numdisc=2 --Sim_pars_cat_nPartVol=1
  --Sim_pars_an_nPartVol=1 --Sim_PartDist_cat_mean=1e-6 --Sim_PartDist_cat_std=0 --Sim_PartDist_an_mean=18e-6
  --Sim_PartDist_an_std=0 --Sim_PartDist_catllfrac=0.2 --Sim_PartDist_anllfrac=0.495
  --Sim_geo_cat_thickness=200e-6 --Sim_geo_an_thickness=243e-6 --Sim_geo_sep_thickness=50e-6
  --Sim_geo_cat_volload=0.849 --Sim_geo_an_volload=0.956 --Sim_geo_cat_por=0.3 --Sim_geo_an_por=0.3
  --Sim_geo_sep_por=0.4 --Sim_elprop_SMpropset=LiClO4_PC 
.RE

Example 2: To input parameter configuration files (used by legacy mpet code) through mpetUI

.PP
.nf
.RS
These files can be input through GUI mode using
  $mpetUI --gui
1. In the GUI navigate to 'MPET simulation launch' menu,
2. Check the overwrite data with parameter configuration file/files to 'True'
3. Specify file by clicking 'Browse' button.

This allows the user to input parameter configuration files through the GUI. 

OR

The parameter configuratuon files can be input through command line mode using the following command.
Say if we want to input the Anode and Cathode configuration file
  $mpetUI --Anode_config_file= <path to the file> --Cathode_config_file= <path to the file>
.RE
.fi
.PP


.SH EXIT STATUS
While using command line mode, if the parameter name doesnt match the UI parameters the program exits showing the possible name of the misspelled parameter name. 
.br
.SH BUGS
No known bugs yet.
.SH AUTHORS
Surya Mitra (sayalaso@purdue.edu), Edwin Garcia (redwing@purdue.edu).
.SH COPYRIGHT
-------------
.PP
Copyright (c) 2020 ------------
.PP
This document is part of the mpetUI software.
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentationles (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

SEE ALSO mpetviz, mpet, dualfoil, vkml, gibbs, ...
