FROM python:3.10-bullseye

#Install necessary packages for daetools
RUN apt-get update && \
    apt-get install --yes libgl1-mesa-glx libgfortran5

#Download and install daetools
RUN wget https://sourceforge.net/projects/daetools/files/daetools/2.0.0/daetools-2.0.0-gnu_linux-x86_64.zip && \
    unzip daetools-2.0.0-gnu_linux-x86_64.zip && \
    pip install ./daetools-2.0.0-gnu_linux-x86_64 && \
    rm -r ./daetools*
