name: MPET code style check

on: [push, workflow_dispatch]

jobs:
  codestyle:

    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      
      - name: Checkout MPET
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: mpet

      - name: Install additional dependencies
        run: |
          pip install flake8

      - name: Check code style
        run: |
          cd mpet
          flake8

